#!/usr/bin/env python3
import sys
import json
from datetime import datetime

def is_int(s):
    try:
        int(s)
        return True
    except ValueError:
        return False

def is_float(s):
    try:
        float(s)
        return not is_int(s)
    except ValueError:
        return False

def is_date(s):
    try:
        datetime.strptime(s, "%Y-%m-%d")
        return True
    except ValueError:
        return False

def is_json(s):
    try:
        obj = json.loads(s)
        return isinstance(obj, dict)
    except:
        return False

def main():
    lines = [line.rstrip("\n") for line in sys.stdin]

    if not lines:
        return

    if all(is_int(l) for l in lines):
        sorted_lines = sorted(lines, key=int)

    elif all(is_float(l) for l in lines):
        sorted_lines = sorted(lines, key=float)

    elif all(is_date(l) for l in lines):
        sorted_lines = sorted(lines, key=lambda d: datetime.strptime(d, "%Y-%m-%d"))

    elif all(is_json(l) for l in lines):
        sorted_lines = sorted(lines, key=lambda x: list(json.loads(x).keys())[0])

    else:
        sorted_lines = sorted(lines, key=str.lower)

    for l in sorted_lines:
        print(l)

if __name__ == "__main__":
    main()
